app/routes.py
from flask import redirect, render_template, request, url_for, flash, Blueprint
from app import db
from app.models import Cars, User, Order
from forms import CarForm, RegisterForm, LoginForm, OrderForm
from config import Config
import os
from flask_login import login_required, login_remembered, login_user, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

bp = Blueprint("main", __name__)
UPLOAD_FOLDER_CARS = Config.UPLOAD_FOLDER_CARS
UPLOAD_FOLDER_USERS = Config.UPLOAD_FOLDER_USERS

# ...............................................................................
@bp.context_processor
def inject_form():
    return dict(registerform=RegisterForm())

@bp.context_processor
def inject_form():
    return dict(loginform=LoginForm())

@bp.route('/')
def home():
    return render_template('home.html')

def add_user_orders(user_phone, user_id):
    orders = Order.query.filter_by(user_phone=user_phone).all()
    for order in orders:
        order.user_id = user_id  # Обновляем каждый заказ
    db.session.commit()


@bp.route('/register', methods=["GET", "POST"])
def register():
    registerform = RegisterForm()

    if registerform.validate_on_submit():
        hashed_password = generate_password_hash(registerform.user_password.data)
        
        new_user = User(
            user_name=registerform.user_name.data,
            user_password=hashed_password,
            user_phone=registerform.user_phone.data,
            user_email=registerform.user_email.data
        )
        
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user)
        flash("Ви успішно зареєструвалися! Ви увійшли до аккаунту.", 'success')
        
        db.session.close()
        
        add_user_orders(new_user.user_phone, new_user.id)
        
        return redirect(url_for("main.home"))

@bp.route('/login', methods=["GET", "POST"])
def login():
    loginform = LoginForm()

    if loginform.validate_on_submit():
        user = User.query.filter_by(user_email=loginform.user_email.data).first()

        if user and check_password_hash(user.user_password, loginform.user_password.data):
            login_user(user)
            flash("Ви увійшли до аккаунту!", 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Неправильно написана пошта або пароль! Спробуйте ще раз.', 'danger')
            return redirect(url_for('main.home'))


@bp.route('/add_new_car', methods=["POST", "GET"])
def add_new_car():
    form = CarForm()
    
    if form.validate_on_submit():
        file = form.image.data
        if file:
            filestorage = os.path.join(UPLOAD_FOLDER_CARS, file.filename)
            with open(filestorage, 'wb') as f:
                f.write(file.read())
        
        new_car = Cars(car=form.car.data, brand=form.brand.data, price=form.price.data, body=form.body.data, image=file.filename)
        db.session.add(new_car)
        db.session.commit()
        return redirect(url_for('main.home'))

    return render_template("add_new_car.html", form=form)


@bp.route('/cars', methods=["GET"])
def cars():
    cars = Cars.query.all()

    return render_template("cars.html", cars=cars)




@bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Ви вийшли з профілю!", 'success')
    return redirect(url_for("main.home"))

@bp.route("/my_profile/<string:user_name>", methods=["GET", "POST"])
@login_required 
def my_profile(user_name):

    user = User.query.filter_by(user_name=user_name).first()
    if not user:
        flash('Користувача не знайдено!', 'warning')
        return redirect(url_for('main.home'))

    return render_template("my_profile.html", user=user)

@bp.route('/cars/create-order/<int:car_id>', methods=["GET", "POST"])
def create_order(car_id):
    form = OrderForm()
    car = Cars.query.filter_by(id=car_id).first()

    # Проверка существования автомобиля
    if car is None:
        flash("Машину не знайдено!", "error")
        return redirect(url_for('main.home'))
    
    if current_user.is_authenticated:
        del form.user_phone

    if form.validate_on_submit():
        total_price = float(form.total_price.data)

        if current_user.is_authenticated:
            user_id = current_user.id
            user_phone = current_user.user_phone
        else:
            user_id = None  # Указываем, что у незарегистрированного пользователя нет ID
            user_phone = form.user_phone.data # Используем номер телефона из формы
            

        # Преобразование даты в строку и времени в строку
        start_date_str = form.start_date.data.strftime('%Y-%m-%d')  # Дата в строку 'YYYY-MM-DD'
        start_time_str = form.start_time.data.strftime('%H:%M:%S')  # Время в строку 'HH:MM:SS'

        stop_date_str = form.stop_date.data.strftime('%Y-%m-%d')  # Дата в строку 'YYYY-MM-DD'
        stop_time_str = form.stop_time.data.strftime('%H:%M:%S')  # Время в строку 'HH:MM:SS'

        # Объединение даты и времени
        start_datetime_str = start_date_str + ' ' + start_time_str
        stop_datetime_str = stop_date_str + ' ' + stop_time_str

        # Преобразование строки в объект datetime
        start_date = datetime.strptime(start_datetime_str, '%Y-%m-%d %H:%M:%S')
        stop_date = datetime.strptime(stop_datetime_str, '%Y-%m-%d %H:%M:%S')

        new_order = Order(
            car_id=car_id,
            start_date=start_date,
            stop_date=stop_date,
            total_price=total_price,
            user_id=user_id,
            user_phone=user_phone
        )

        
        
        db.session.add(new_order)
        db.session.commit()
        flash("Замовлення створено успішно!", "success")
        return redirect(url_for('main.home'))


    return render_template('create_order.html', form=form, car=car)

@bp.route('/edit')
def edit():

    cars = Cars.query.all()  # Получаем все машины из базы данных
    return render_template("edit.html", cars=cars)

@bp.route('/edit/del<int:car_id>')
def delete(car_id):
    car = Cars.query.filter_by(id=car_id).first_or_404()

    # Обрабатываем заказы, связанные с этим автомобилем
    orders = Order.query.filter_by(car_id=car_id).all()
    for order in orders:
        # Можно либо удалить заказы, либо обновить их, назначив другой car_id
        db.session.delete(order)  # Если нужно удалить заказы

    db.session.delete(car)
    db.session.commit()
    return redirect(url_for("main.edit"))

app/templates/add_new_car.html
{% extends "base.html"%}

{% block content %}

<div>
    <form method="POST" action="{{url_for('main.add_new_car')}}" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <div class="mb-3">
        {{form.car.label}}
        {{form.car(class="form-control")}}

        {{form.brand.label}}
        {{form.brand(class="form-control")}}

        {{form.price.label}}
        {{form.price(class="form-control")}}

        {{form.body.label}}
        {{form.body(class="form-control")}}

        {{form.image.label}}
        {{form.image(class="form-control")}}

        {{form.submit.label}}
        {{form.submit(class="form-control")}}
        </div>

    </form>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='styles/styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exo+2:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js"></script>
</head>
<body>
    <header class="navbar navbar-expand-lg navbar-dark px-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img class="logo-img" src="static/photos/logo/logo3.png" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto navlist">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == url_for('main.home') %}active{% endif %}" href="{{ url_for('main.home') }}">Головна</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == url_for('main.cars') %}active{% endif %}" href="{{ url_for('main.cars') }}">Авто</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == url_for('main.my_profile', user_name=current_user.user_name) %}active{% endif %}" href="{{ url_for('main.my_profile', user_name=current_user.user_name) }}">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.logout') }}">Вийти</a>
                    </li>
                    {% else %}
                    <li class="nav-item" style="  padding-right: 8px;  margin-bottom: 8px;">
                        <a class="btn btn-primary" style="background-color: rgb(3, 21, 21);" id="auth-btn">Увійти</a>
                    </li>
                    <li class="nav-item" style="  padding-right: 8px; margin-bottom: 8px;">
                        <a class="btn btn-secondary" style="background-color: rgb(3, 21, 21);" id="register-btn">Зареєструватися</a>
                    </li>
                    {% endif %}
                    {%if current_user.is_admin %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == url_for('main.add_new_car') %}active{% endif %}" href="{{ url_for('main.add_new_car') }}">Додати авто</a>
                    </li>
                    <li class="nav-item" style="  padding-right: 8px; margin-bottom: 8px;">
                        <a class="btn btn-secondary" style="background-color: rgb(3, 21, 21);" href="{{ url_for('main.edit') }}">Редагування</a>
                    </li>
                    {% endif %}

                </ul>
            </div>
        </div>
    </header>
    
    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="toast align-items-center text-white bg-{{ category }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="d-flex">
                            <div class="toast-body">
                                {{ message }}
                            </div>
                            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // Инициализируем все тосты на странице
            var toastElements = document.querySelectorAll('.toast');
            toastElements.forEach(function(toastElement) {
                var toast = new bootstrap.Toast(toastElement, { autohide: true, delay: 5000 }); // 5 секунд задержка
                toast.show();  // Отображаем тост
            });
        });
    </script>

    <main  >
        {% block content %}
        {% endblock %}

        {% if current_user.is_authenticated %}
        {% else %}
        <div class="popup_auth_wrapper popup_hide" id="popup-auth-wrapper">
            <div class="popup_auth_container">
                <div class="popup_auth_header">
                    <h3>Авторизуватися</h3>
                    <span id="popup-auth-close">×</span>
                </div>
                <div class="popup_auth_content">
                    <form action="{{ url_for('main.login') }}" method="POST">
                        {{ loginform.hidden_tag() }}
                        <div class="mb-3">
                            {{ loginform.user_email.label(class="form-label") }}
                            {{ loginform.user_email(class="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ loginform.user_password.label(class="form-label") }}
                            {{ loginform.user_password(class="form-control") }}
                        </div>
                        <button type="submit" class="btn btn-primary">{{ loginform.submit.label }}</button>
                    </form>
                </div>
            </div>
        </div>

        <div class="popup_auth_wrapper popup_hide" id="popup-register-wrapper">
            <div class="popup_auth_container">
                <div class="popup_auth_header">
                    <h3>Зареєструватися</h3>
                    <span id="popup-register-close">×</span>
                </div>
                <div class="popup_auth_content">
                    <form action="{{ url_for('main.register') }}" method="POST">
                        {{ registerform.hidden_tag() }}
                        <div class="mb-3">
                            {{ registerform.user_name.label(class="form-label") }}
                            {{ registerform.user_name(class="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ registerform.user_email.label(class="form-label") }}
                            {{ registerform.user_email(class="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ registerform.user_phone.label(class="form-label") }}
                            {{ registerform.user_phone(class="form-control", id="user_phone", placeholder="ХХХ-XXX-XX-XX") }}
                        </div>
                        <div class="mb-3">
                            {{ registerform.user_password.label(class="form-label") }}
                            {{ registerform.user_password(class="form-control") }}
                        </div>
                        <button type="submit" class="btn btn-primary">{{ registerform.submit.label }}</button>
                    </form>
                </div>
            </div>
        </div>
        {% endif %}
    </main>

    <footer class="footer text-light">
        <div class="container p-4">
            <div class="footer_row d-flex justify-content-center">
                <div class="footer_col">
                    <div class="footer__col_container">
                        <a class="navbar-brand" href="/">U-Motor</a>
                        <p>Copyright © 2024  U-Motor.com.ua</p>
                        <span>Усі права під захистом.</span>
                    </div>
                </div>
                <div class="footer_col">
                    <div class="container-fluid block-social-icons">
                        <p class="social-icons-text">Наші соц. мережі</p>
                        <div class="social-icons">
                            <a href="https://t.me/desinspire" target="_blank" class="icon link__icon">
                                <i class="fab fa-telegram-plane"></i> <span>Telegram</span>
                            </a>
                            
                            <a href="https://www.tiktok.com" target="_blank" class="icon link__icon">
                                <i class="fab fa-tiktok"></i> <span>Tik Tok</span>
                            </a>
    
                            <a href="https://www.instagram.com" target="_blank" class="icon link__icon">
                                <i class="bi bi-instagram"></i> <span>Instagram</span>
                            </a>
                        </div>
                    </div>
    
                    <div class="container-fluid block-online-support">
                        <p class="online-support-text">Онлайн підтримка 24/7</p>
                        <div class="online-support">
                            <p>Пошта: <span><a href="mailto:koshchinmaxim06@gmail.com" >koshchinmaxim06@gmail.com</a></span></p>
                            <p><i class="bi bi-phone"></i><span class="phone">067-199-40-95</span></p>
                            <p><i class="bi bi-phone"></i><span class="phone">066-115-82-12</span></p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script>
        // Проверяем, существует ли поле телефона
        const phoneInput = document.getElementById('user_phone');
        
        if (phoneInput) {
          // Форматирование ввода с дефисами
          phoneInput.addEventListener('input', function (e) {
            let x = e.target.value.replace(/\D/g, '').match(/(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2})/);
            e.target.value = (x[1] ? x[1] : '') + (x[2] ? '-' + x[2] : '') + (x[3] ? '-' + x[3] : '') + (x[4] ? '-' + x[4] : '');
          });
        }
    </script>


    <script>
        const popupCloseAuthBtn = document.getElementById('popup-auth-close')
        const popupAuthWrapper = document.getElementById('popup-auth-wrapper')

        const popupCloseRegisterBtn = document.getElementById('popup-register-close')
        const popupRegisterWrapper = document.getElementById('popup-register-wrapper')

        const authBtn = document.getElementById('auth-btn')
        const registerBtn = document.getElementById('register-btn')


        // Авторизация
           authBtn.addEventListener('click', () => {
                popupAuthWrapper.classList.remove('popup_hide')
                popupAuthWrapper.classList.add('popup_show')
            })

            popupCloseAuthBtn.addEventListener('click', () => {
                popupAuthWrapper.classList.remove('popup_show')
                setTimeout(() => {
                    popupAuthWrapper.classList.add('popup_hide')
                }, 300)
            })

        // Регистрация
        registerBtn.addEventListener('click', () => {
            popupRegisterWrapper.classList.remove('popup_hide')
            popupRegisterWrapper.classList.add('popup_show')
        })

        popupCloseRegisterBtn.addEventListener('click', () => {
            popupRegisterWrapper.classList.remove('popup_show')
            setTimeout(() => {
                popupRegisterWrapper.classList.add('popup_hide')
            }, 300)
        })
    </script>
</body>
</html>

app/templates/cars.html
{% extends "base.html" %}

{% block content %}

<h3 class="car-text-h text-center cars__title">Машини U-Motor</h3>
<div class="main-car-card">
  <div id="carCarousel" class="carousel slide container-fluid" >
    <div class="carousel-inner">
        {% for car in cars %}
        <div class="carousel-item {% if loop.first %}active{% endif %}">
            <div class="car-card container-fluid d-flex" style="max-width: 170vh; margin: auto; align-items: center;">
                <div class="image-container d-flex align-items-center" style="flex: 1;">
                    <img src="{{ url_for('static', filename='photos/cars/' + car.image) }}" class="card-img-top" alt="{{ car.car }}">
                </div>
                <div class="text-container container-fluid" style="flex: 1;">
                    <p class="car-text">Машина: {{ car.car }}</p>
                    <p class="car-text">Марка: {{ car.brand }}</p>
                    <p class="car-text">Тип: {{ car.body }}</p>
                    <p class="car-text">Ціна: {{ car.price }} грн/год</p>
                    <a href="{{url_for('main.create_order', car_id=car.id)}}">
                        <button class="car-bt">Орендувати</button>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <button class="carousel-control-prev slider__button" type="button" data-bs-target="#carCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon " aria-hidden="true"></span>
        <!--        Prev-->
    </button>
    <button class="carousel-control-next slider__button" type="button" data-bs-target="#carCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon " aria-hidden="true"></span>
        <!--        Next-->
    </button>
    </div>
</div>

<!-- Include Bootstrap CSS and JS (add this to your <head> or at the end of your <body>) -->
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</div>



{% endblock %}

app/templates/create_order.html
{% extends "base.html" %}

{% block title %}
Створення замовлення
{% endblock %}

{% block content %}
<div class="order-container">
    <h1 class="text-center title">Створити замовлення</h1>
    
    <form action="{{ url_for('main.create_order', car_id=car.id) }}" method="POST">
        <!-- CSRF-токен -->
        {{ form.hidden_tag() }}

        <div class="order-car-container">
            <div class="order-car-column-title">
                <div class="order-car-container-img">
                    <div class="container-fluid" style="padding-left: 0px;">
                        <img src="{{ url_for('static', filename='photos/cars/' + car.image) }}" class="card-img-top" alt="{{ car.car }}">
                    </div>
                </div>
                <div class="order-car-container-text">
                    <p class="car-text">Машина: {{ car.car }}</p>
                    <p class="car-text">Марка: {{ car.brand }}</p>
                    <p class="car-text">Тип: {{ car.body }}</p>
                    <p class="car-text" id="price">Ціна: {{ car.price }} грн/год</p>
                    <p class="car-text" id="total-price">Всього до сплати: 0 грн</p>
                </div>
            </div>
            
            <div class="order-car-column-form">
                <div class="date">
                    {% if not current_user.is_authenticated %}
                        <!-- Добавляем поле для телефона, если пользователь не авторизован -->
                        {{ form.user_phone.label }} {{ form.user_phone(id="user_phone", placeholder="ХХХ-XXX-XX-XX") }}
                    {% endif %}
                    
                    <!-- Поля для выбора даты и времени -->
                    {{ form.start_date.label }} {{ form.start_date(class="custom-date-picker", id='start-date') }}
                    {{ form.start_time.label }} {{ form.start_time(class="custom-time-picker", id='start-time') }}
                    {{ form.stop_date.label }} {{ form.stop_date(class="custom-date-picker", id='stop-date') }}
                    {{ form.stop_time.label }} {{ form.stop_time(class="custom-time-picker", id='stop-time') }}

                </div>

                <!-- Скрытое поле для хранения общей цены -->
                {{ form.total_price(id='total_price') }}

                <div class="buttons">
                    <!-- Кнопка для расчета цены -->
                    <button type="button" class="submit__button" id="button_price" onclick="calculatePrice()">Розрахувати ціну</button>

                    <!-- Кнопка для отправки формы -->
                    {{ form.submit(class="submit__button hide", id="button_submit") }}
                </div>
            </div>
        </div>
    </form>

</div>

<script>
    // Проверяем, существует ли поле телефона
    const phoneInput = document.getElementById('user_phone');
    
    if (phoneInput) {
      // Форматирование ввода с дефисами
      phoneInput.addEventListener('input', function (e) {
        let x = e.target.value.replace(/\D/g, '').match(/(\d{0,3})(\d{0,3})(\d{0,2})(\d{0,2})/);
        e.target.value = (x[1] ? x[1] : '') + (x[2] ? '-' + x[2] : '') + (x[3] ? '-' + x[3] : '') + (x[4] ? '-' + x[4] : '');
      });
    }
</script>

<!-- Инициализация Flatpickr для выбора даты -->
<script>
    flatpickr(".custom-date-picker", {
        dateFormat: "Y-m-d",
        locale: "ru"
    });
</script>

<!-- Инициализация jQuery Timepicker с поддержкой прокрутки -->
<script>
    $(document).ready(function(){
        $('.custom-time-picker').timepicker({
            timeFormat: 'H:i',  // 24-часовой формат
            interval: 15,  // Шаг изменения минут
            minTime: '0',  // Начальное время
            maxTime: '23:59',  // Конечное время
            startTime: '00:00',  // Начало отсчета
            dynamic: true,  // Адаптивный интерфейс
            dropdown: true,  // Выпадающий список времени
            scrollbar: true  // Прокрутка для выбора времени
        });
    });
</script>

<!-- Скрипт для расчета цены -->
<script>
    function calculatePrice() {
        const btnPrice = document.getElementById('button_price'); // Кнопка "Рассчитать цену"
        const btnSubmit = document.getElementById('button_submit'); // Кнопка "Создать заказ"
    
        const startDate = new Date(`${document.getElementById("start-date").value}T${document.getElementById("start-time").value}`);
        const stopDate = new Date(`${document.getElementById("stop-date").value}T${document.getElementById("stop-time").value}`);
        
        if (isNaN(startDate) || isNaN(stopDate)) {
            alert("Пожалуйста, введите корректные даты и время.");
            return false;
        }
    
        if (startDate >= stopDate) {
            alert("Дата и время окончания должны быть позже даты и времени начала.");
            return false;
        }
    
        // Расчет разницы во времени в часах
        const hours = Math.ceil((stopDate - startDate) / (1000 * 60 * 60)); // Разница в часах
        const pricePerHour = {{ car.price }}; // Цена за час
        const totalPrice = hours * pricePerHour; // Общая цена
    
        // Обновление отображаемой общей цены
        document.getElementById("total-price").innerText = `Итого: ${totalPrice} грн`;
    
        // Обновление значения в поле формы total_price
        document.getElementById("total_price").value = totalPrice;
    
        // Скрываем кнопку "Рассчитать цену"
        btnPrice.classList.add('hide');
    
        // Показываем кнопку для отправки формы "Создать заказ"
        btnSubmit.classList.remove('hide');
    }
</script>

{% endblock %}

app/templates/edit.html
{% extends "base.html"%}

{% block content %}
{%for car in cars%}
<div class="container-fluid">
    <div class="container-fluid" style="padding-left: 0px;">
        <img src="{{ url_for('static', filename='photos/cars/' + car.image) }}" class="card-img-top" alt="{{ car.car }}">
    </div>
    <div class="container-fluid" >
        <p class="car-text">{{ car.brand }}</p>
        <p class="car-text">{{ car.body }}</p>
        <p class="car-text">{{ car.price }} грн/год</p>
        <a href="{{url_for('main.delete', car_id=car.id)}}">
            <button>Delete</button>
        </a>
    </div>
</div>
</div>
{%endfor%}
{% endblock %}

app/templates/my_profile.html
{% extends "base.html" %}

{% block title %}
Профиль пользователя
{% endblock %}

{% block content %}
<div class="profile__wrapper">
    <div class="profile-container">
        <!-- Блок с информацией о пользователе -->
        <div class="profile-header">
            <img src="{{ url_for('static', filename='/photos/users/' + user.user_photo) }}" alt="{{ user.user_name }}" class="avatar">
            <div class="user-info">
                <h1>{{ user.user_name }}</h1>
                <p>Телефон: {{ user.user_phone }}</p>
                <p>Email: {{ user.user_email }}</p>
            </div>
        </div>
    </div>
    <!-- История заказов -->
    <div class="order-history">
        <h2>Історія замовлень</h2>
        <table>
            <thead>
            <tr>
                <th>Машина</th>
                <th>Дата</th>
                <th>Час</th>
                <th>Ціна</th>
            </tr>
            </thead>
            <tbody>
            {% for order in user.orders %}
            <tr>
                <td>{{ order.car.brand }} {{ order.car.car }}</td>
                <td>{{ order.start_date.strftime('%d.%m.%Y') }} - {{ order.stop_date.strftime('%d.%m.%Y') }}</td>
                <td>{{ order.start_date.strftime('%H:%M') }} - {{ order.stop_date.strftime('%H:%M') }}</td>
                <td>{{ order.total_price }} грн.</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}